### PR TITLE
Support for Loongarch64

### PR DESCRIPTION
**Pull request by wenghongquan**
Suit for devel (nim-lang/Nim#19223)
Add cpu loongarch64 in build.sh, makefile and c_code for build success in loongarch PC.

All I have done is:
1. add cpu loongarch64 in build.sh
2. add cpu loongarch64 in makefile
3. create new folder 2_20 for loongarch64 in linux
4. add TM__LEa0rTUoGHqcCT74IoUuTg_94 for loongarch64 in @mplatform.nim.c
5. extend array tyArray__hsHGImvImZtnKKlj0Ycm2Q, CPU__uYXopJX8pM87pQDCtmgWfQ, , TM__LEa0rTUoGHqcCT74IoUuTg_4, TM__LEa0rTUoGHqcCT74IoUuTg_0 in @mplatform.nim.c
6. extend array TM__LEa0rTUoGHqcCT74IoUuTg_3_27 and alter it to new name TM__LEa0rTUoGHqcCT74IoUuTg_3_28 in @mplatform.nim.c
7. extend array tyArray__hsHGImvImZtnKKlj0Ycm2Q in @mccgutils.nim.c, @mcgen.nim.c, @mcommands.nim.c, @mextccomp.nim.c, @moptions.nim.c, @msemfold.nim.c

please review it, thanks!

### CODE REVIEW

**Comment by Araq** [comment]
This has all been automated, don't touch this code. You need to patch compiler.ini and run the appropriate steps which I forgot. But then I don't want to review your diff either (it would be much too risky, sorry!) so I have to do myself. Ping me again in 4 days if I haven't done it by then.

**Comment by wenghongquan** [comment]
> This has all been automated, don't touch this code. You need to patch compiler.ini and run the appropriate steps which I forgot. But then I don't want to review your diff either (it would be much too risky, sorry!) so I have to do myself. Ping me again in 4 days if I haven't done it by then.

That is great.

**Comment by wenghongquan** [comment]
> This has all been automated, don't touch this code. You need to patch compiler.ini and run the appropriate steps which I forgot. But then I don't want to review your diff either (it would be much too risky, sorry!) so I have to do myself. Ping me again in 4 days if I haven't done it by then.

hey Araq, have you finished it?

**Comment by Araq** [comment]
Sorry, please I'll do it this weekend. If not ping me again on Monday.

**Comment by ringabout** [comment]
update?

**Comment by loongson-zn** [comment]
hi @Araq ,  Do you have any problem during the process?

**Comment by loongson-zn** [comment]
Hi @Araq , if these files need to be automatically generated, you can refer to https://wiki.debian.org/LoongArch/sbuildQEMU  to build the environment.
If Nim wants to successfully support loong64, we need your help. [Nim build in debian status](https://buildd.debian.org/status/package.php?p=nim&suite=sid)

**Comment by ringabout** [comment]
Well, `Loongarch64` has been supported by https://github.com/nim-lang/csources_v2, which has been used for Nim 2.0

**Comment by loongson-zn** [comment]
Wow,  very good!  About 1.6.14 version in debian, is there a good way to push it forward? 
https://buildd.debian.org/status/package.php?p=nim&suite=sid

**Comment by loongson-zn** [comment]
Perhaps, you can tell me a method how to automate the generation of the files in v1 version

**Pull request closed without merging**
